### ISSUE TITLE
Error at DeepDream demo [prototxtParser is not defined]

### ISSUE THREAD

**Issue by ad48hp** [chaosmail/caffejs#27]
Got this error, while tried to run DeepDream [thing](https://chaosmail.github.io/caffejs/deepdream.html) in two browsers (Opera & Chrome)..

```
Uncaught (in promise) ReferenceError: prototxtParser is not defined
    at PrototxtParser.parseString (caffe.js:6029)
    at caffe.js:2054
```

**Comment by chaosmail** [comment]
thanks for reporting this error! I fixed it and it should work again :)

once it is runing, it should look like this:
![Bildschirmfoto vom 2020-01-09 19-18-23](https://user-images.githubusercontent.com/2969388/72097748-f8843d80-3314-11ea-81e4-486b662ac0e3.png)
