### ISSUE TITLE
How to get get bvlc_googlenet weight?

### ISSUE THREAD

**Issue by ghost** [chaosmail/caffejs#4]
hi, when I run convert_caffemodel.py to load weight from bvlc_googlenet.caffemodel I get No module named fs..thank you.

**Comment by chaosmail** [comment]
Hi @prouster 
you can either convert the Caffe GoogLeNet weights yourself using the function in `scripts/convert_caffemodel.py` or copy them from the `gh-pages` branch.

    git checkout gh-pages
    cp models/bvlc_googlenet/weights -R ~/googlenet
    git checkout master
    cp ~/googlenet docs/assets/models/bvlc_googlenet/weights

**Comment by ghost** [comment]
thanks for your prompt feedback!
