### ISSUE TITLE
Getting started - Errors when running npm commands

### ISSUE THREAD

**Issue by atenpas** [chaosmail/caffejs#6]
When I run _npm start_, I get this:

> caffejs@0.1.0 start /home/andreas/software/caffejs
> cd docs-pages && http-server
> 
> sh: 1: cd: can't cd to docs-pages

And when I run npm install, I get this:

> 
> typings install
> 
> typings WARN deprecated 5/9/2016: "registry:dt/dagre#0.7.0+20160505164908" is deprecated (updated, replaced or removed)
> typings WARN deprecated 9/6/2016: "registry:dt/d3#0.0.0+20160620220125" is deprecated (updated, replaced or removed)
> typings WARN deprecated 10/4/2016: "registry:dt/whatwg-fetch#0.0.0+20160524142046" is deprecated (updated, replaced or removed)

**Comment by chaosmail** [comment]
Hi @atenpas 

right now it's a bit weird to get started, you have to compile the docs running `gulp docs`. This requires to have gulp and typescript installed (`npm install -g gulp-cli typescript typings`). Now `npm install` and `npm start` should work.

Another great option to play around with CaffeJS is to just checkout the gh-pages branch (the one that is hostet here https://chaosmail.github.io/caffejs/) via `git checkout gh-pages`. Now you should be able to spin up a local webserver via `http-server` (once it is installed via `npm install -g http-server`).

Hope this helps you!

Best,
Christoph
